name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pdf2pptx
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Convert PDF to PPTX
      run: |
        for file in pdf-files/*.pdf; do
          filename=$(basename "$file".pdf)
          if [! -f "pdf-files/${filename}.pptx" ]; then
            pdf2pptx "$file"
          fi
        done
    - name: Upload PPTX files as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: generated-pptx
        path: pdf-files/*.pptx
